name: R-CMD-check

on:
  push:
    branches: [main, latest]
  pull_request:
    branches: [main, latest]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2' # current R version

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::rcmdcheck
          any::remotes

    - name: Run R CMD check
      run: |
        R CMD build .
        R CMD check *.tar.gz --no-manual --no-build-vignettes

